name: grafana-agent
version: '0.40.4'
summary: A telemetry collector for sending metrics, logs, and trace data
license: Apache-2.0
contact: simon.aronsson@canonical.com
issues: https://github.com/canonical/grafana-agent-snap/issues
source-code: https://github.com/canonical/grafana-agent-snap
website: https://grafana.com
description: "Grafana Agent is a telemetry collector for sending metrics, \nlogs, and trace data to the opinionated Grafana observability stack.\n"
base: core22
grade: stable
confinement: strict
compression: lzo
plugs:
  etc-grafana-agent:
    interface: system-files
    read:
      - /etc/grafana-agent.yaml
  logs:
    interface: content
    target: $SNAP/shared-logs
  proc-sys-kernel-random:
    interface: system-files
    read:
      - /proc/sys/kernel/random/write_wakeup_threshold
      - /proc/sys/kernel/random/read_wakeup_threshold
      - /proc/sys/kernel/random/poolsize
      - /proc/sys/kernel/random/urandom_min_reseed_secs
apps:
  grafana-agent:
    daemon: simple
    command: agent-wrapper
    install-mode: disable
    restart-condition: on-failure
    plugs:
      - network-bind
      - time-control
      - hardware-observe
      - mount-observe
      - network-observe
      - system-observe
      - log-observe
      - etc-grafana-agent
      - proc-sys-kernel-random
architectures:
  - build-on: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

parts:
  wrapper:
    plugin: dump
    source: ./snap/local
    source-type: local
    override-build: |
      cp agent-wrapper $CRAFT_PART_INSTALL/
  grafana-agent:
    plugin: go
    source: https://github.com/grafana/agent
    source-type: git
    source-tag: "v0.40.4"
    build-snaps:
      - go
    build-packages:
      - build-essential
      - libsystemd-dev
      - libbpfcc-dev
      - bpfcc-tools
      - on amd64 to arm64:
        - gcc-aarch64-linux-gnu
        - linux-libc-dev-arm64-cross
        - libc6-dev-arm64-cross
    build-environment:
      - to amd64:
        - GOOS: linux
        - GOARCH: amd64
      - to arm64:
        - GOOS: linux
        - GOARCH: arm64
        - CC: /usr/bin/aarch64-linux-gnu-gcc
    stage-packages:
      - libsystemd0
      - libbpfcc
      - bpfcc-tools
    override-build: |
      export USE_CONTAINER=0
      export GOFLAGS="-mod=readonly -tags=promtail_journal_enabled"

      make agent agentctl

      cp build/grafana-agent $CRAFT_PART_INSTALL/agent
      cp build/grafana-agentctl $CRAFT_PART_INSTALL/agentctl
