# Build the snap on pull_request to ensure the snap is buildable before merge to main
#
# This workflow duplicates some of the logic from release-snap.yaml.  If modifying this workflow,
# ensure that release-snap.yaml is also updated
name: Test Build Snap

on:
  pull_request:

env:
  SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform:
          - amd64
          - arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.1
        with:
          channel: latest/stable

      - name: Install dependencies
        run: |
          sudo snap install --classic --channel edge snapcraft

      - name: Build Snap (${{ matrix.platform }})
        run: snapcraft pack --build-for=${{ matrix.platform }}
